const symbolList: string[] = [
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'ADAUSDT',
  'SOLUSDT', 'DOGEUSDT', 'AVAXUSDT', 'DOTUSDT', 'MATICUSDT',
  'LTCUSDT', 'SHIBUSDT', 'TRXUSDT', 'LINKUSDT', 'ATOMUSDT',
  'BCHUSDT', 'XLMUSDT', 'XMRUSDT', 'ETCUSDT', 'NEARUSDT',
  'FILUSDT', 'ICPUSDT', 'SANDUSDT', 'APTUSDT', 'HBARUSDT',
  'AAVEUSDT', 'EGLDUSDT', 'IMXUSDT', 'ALGOUSDT', 'GRTUSDT',
  'FTMUSDT', 'RNDRUSDT', 'FLOWUSDT', 'THETAUSDT', 'ARBUSDT',
  'CRVUSDT', 'DYDXUSDT', 'CHZUSDT', 'PEPEUSDT', 'LDOUSDT',
  'OPUSDT', 'TWTUSDT', 'WLDUSDT', 'INJUSDT', 'JOEUSDT',
  'KLAYUSDT', 'MASKUSDT', 'COTIUSDT', 'ZILUSDT','1000PEPEUSDT', 'ENSUSDT'
];

export default symbolList;
